### ISSUE TITLE
fix tests on CI (related to cross platform rendering of multiline messages)

### ISSUE THREAD

**Issue by yashaka** [yashaka/NSelene#101]
currently 62 tests passes locally on mac executed via `dotnet test`, but fails on CI. Fix it:)

Here is the example of failure:
```
  Failed Type_IsRenderedInError_OnOverlappedWithOverlayFailure [285 ms]
  Error Message:
     Expected: String containing "Timed out after 0.25s, while waiting for:
	Browser.Element(input).ActualNotOverlappedWebElement.SendKeys(and after)
Reason:
	Element: <input value="before ">
	is overlapped by: <div id="overlay""
  But was:  "Timed out after 0.25s, while waiting for:
	Browser.Element(input).ActualNotOverlappedWebElement.SendKeys(and after)
Reason:
	Element: <input value="before ">
	is overlapped by: <div id="overlay" style="
                        display: block;
                        position: fixed;
                        display: block;
                        width: 100%;
                        height: 100%;
                        top: 0;
                        left: 0;
                        right: 0;
                        bottom: 0;
                        background-color: rgba(0,0,0,0.1);
                        z-index: 2;
                        cursor: pointer;
                    ">
                </div>"

  Stack Trace:
     at NSelene.Tests.Integration.SharedDriver.SeleneSpec.SeleneElement_Type_Specs.Type_IsRenderedInError_OnOverlappedWithOverlayFailure() in D:\a\NSelene\NSelene\NSeleneTests\Integration\SharedDriver\SeleneElement_Type_Specs.cs:line 369
```

The weird is – actually texts match:
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/1e879915-d889-4e27-aa07-e5e8136ce4e2">
o_O

Another potential problem to have a solution for - when executed from Testing tab at Visual Studio Code - same tests fail but with another error, similar to:

```
  Failed Type_IsRenderedInError_OnOverlappedWithOverlayFailure [285 ms]
  Error Message:
     Expected: String containing "Timed out after 0.25s, while waiting for:
	Browser.Element(input).ActualNotOverlappedWebElement.SendKeys(and after)
Reason:
	Element: <input value="before ">
	is overlapped by: <div id="overlay""
  But was:  "Timed out after 0,25s, while waiting for:
	Browser.Element(input).ActualNotOverlappedWebElement.SendKeys(and after)
Reason:
	Element: <input value="before ">
	is overlapped by: <div id="overlay" style="
                        display: block;
                        position: fixed;
                        display: block;
                        width: 100%;
                        height: 100%;
                        top: 0;
                        left: 0;
                        right: 0;
                        bottom: 0;
                        background-color: rgba(0,0,0,0.1);
                        z-index: 2;
                        cursor: pointer;
                    ">
                </div>"

  Stack Trace:
     at NSelene.Tests.Integration.SharedDriver.SeleneSpec.SeleneElement_Type_Specs.Type_IsRenderedInError_OnOverlappedWithOverlayFailure() in D:\a\NSelene\NSelene\NSeleneTests\Integration\SharedDriver\SeleneElement_Type_Specs.cs:line 369
```

where the diff is `0.25s` vs `0,25s` o_O

**Comment by wjgerritsen-0001** [comment]
You have two problems here to solve:
- cultural formatting: `0.25` vs `0,25`
- EOL variations: "\n" vs "\r\n" 

Both can vary depending on the execution environment!

For `SeleneElement_Click_Failure_OnHiddenElement` I propose to change the assertion to 
```
                Assert.That(error.Message.Trim(), Does.Contain(
                     $"Timed out after {0.25}s, while waiting for:\n"
                    + "\tBrowser.Element(a).ActualWebElement.Click()\n"
                    + "Reason:\n"
                    + "\telement not interactable"
                ));
```

So follow the system in cultural formatting the `double`, but defining the EOL as done in the `Wait` code.

**Comment by yashaka** [comment]
@wjgerritsen-0001 Hm... good points! 

Yet i would try to keep the error message built with interpolation over concatenation, just for easier support of such assertions of error messages in future... Because then it's a bit simpler to run tests, see failure, ensure it's correct and copy&paste it to the test so it passes... Maybe we can change the implementation of the `Wait` code so just interpolation and `"""` strings is enough...

**Comment by wjgerritsen-0001** [comment]
Congrats!

**Comment by yashaka** [comment]
Last CI job failed for the latest commit fix but that failure was of another issue. Your ideas helped to fix it! Thank you! I changed
* the `Wait` implementation and other places where the `\n` was used (I refactored either to triple-string or Environment.NewLine)
* and `0.25s` to `{{0.25}}s` inside tripple string.

It worked:) Thank you again!
