### ISSUE TITLE
Fix test instability related to timers

### ISSUE THREAD

**Issue by wjgerritsen-0001** [yashaka/NSelene#104]
Sometimes tests are failing because the build server is too slow/fast e.g. https://github.com/yashaka/NSelene/actions/runs/10847342249/job/30102217890?pr=103

>   Failed DoubleClick_Waits_For_NoOverlay_IfCustomized [2 s]
  Error Message:
     Expected: less than 2024-09-13 10:22:17.1450627
  But was:  2024-09-13 10:22:18.2704144
>  Stack Trace:  
>    at NSelene.Tests.Integration.SharedDriver.SeleneSpec.SeleneElement_DoubleClick_Specs.DoubleClick_Waits_For_NoOverlay_IfCustomized() in D:\a\NSelene\NSelene\NSeleneTests\Integration\SharedDriver\SeleneElement_DoubleClick_Specs.cs:line 238
>
>  Failed Hover_Waits_For_NoOverlay_IfCustomized [1 s]
>  Error Message:
>     Expected: less than 2024-09-13 10:22:18.1612626
>  But was:  2024-09-13 10:22:18.2699995
>
>  Stack Trace:
>     at NSelene.Tests.Integration.SharedDriver.SeleneSpec.SeleneElement_Hover_Specs.Hover_Waits_For_NoOverlay_IfCustomized() in D:\a\NSelene\NSelene\NSeleneTests\Integration\SharedDriver\SeleneElement_Hover_Specs.cs:line 238

Solution direction I am thinking of is to make use of ITimeProvider (.Net 8 feature): https://andrewlock.net/exploring-the-dotnet-8-preview-avoiding-flaky-tests-with-timeprovider-and-itimer/

I understand that we cannot programmatically proceed the time in the browser, but still it might solve our stability issues.

Comments?

**Comment by yashaka** [comment]
Hm... How the solution would look like? if use ITimeProvider?

**Comment by wjgerritsen-0001** [comment]
My guess is the the CI server is pretty heavy loaded, so that the time to load the new script and double click and all the interactions using selenium can easily take +1 sec.

Let me try to do a sample implementation and discuss whether stuff becomes too complicated with that.  ;-)

**Comment by yashaka** [comment]
Good good! Looking forward!

**Comment by wjgerritsen-0001** [comment]
The FakeTimeProvider is not rich enough for our purpose, I requested an interface addition: 
- https://github.com/dotnet/extensions/issues/5441
This will take time, so for now we just can increase the timeouts.

**Comment by wjgerritsen-0001** [comment]
@yashaka Please have a look at the above solution direction. It encapsulates testing the timeouts, so a lot of duplicate code can be removed while enforcing that the assertions are everywhere the same.

Another benefit is that this approach is a preparation for using the `FakeTimeProvider` in the future.
